---
title: "Flayer Haters Fantasy Football League Constitution"
author:
- Gregory Dupuis
- Michael Treadwell
date: "`r format(Sys.time(), '%B, %d %Y')`"
output:
  html_document:
    toc: true
    number_sections: true
    theme: journal
    toc_float:
      smooth_scroll: false
---

# League Governance and Authorities

## Authority of the Commissioner

### League Action and Veto Powers {#league-action-and-veto-power}

1. The Fantasy League Commissioner, hereinafter referred to as the Commissioner, will have unilateral authority to make decisions concerning the management and operations of the Flayer Haters Fantasy Football League, hereinafter referred to as the league, with the exception of those statutes outlined in the Flayer Haters Fantasy Football League Constitution, hereinafter referred to as the Constitution. In the event that a dispute or circumstance arises in which action is required and is not strictly outlined within the Constitution the Commissioner shall and will resolve the matter.

2. The Commissioner will also have veto power over any action taken by league members that violates any rule or regulation outlined in the statutes of this Constitution.

3. Any and all actions taken by the Commissioner regarding issues not outlined by the Constitution will be effective immediately; however the action will be subjected to a 3 day review period by the league members. During the review period the league members will have an opportunity to override the decision with a 2/3 (7 member) vote (excluding the Commissioner).
    a. Should a decision by the Commissioner be overridden, the resulting action shall and will be considered final.
    
4. Any and all actions taken by the Commissioner regarding issues not outlined by the Constitution will be effective immediately; however the action will be subjected to a 3 day review period by the league members. During the review period the league members will have an opportunity to override the decision with a 2/3 (7 member) vote (excluding the Commissioner).

###  League Owner Dismissal and Addition

1. The Commissioner has the authority to dismiss an owner from the league at any time should a situation arise. This action will be subject to the 3 day review period regulations outlined in [1.1.1.3](#league-action-and-veto-power)

2. The Commissioner does not have unilateral authority to add an owner to the league should a team become unowned by any action. Regulations for this situation are covered in [2.2](#exiting-owners-new-owners).

### League Violations and Penalties {#league-violations-and-penalties}

1. The Commissioner has the authority to set penalties for any and all rule violations outlined within the statutes of the Constitution. Any penalty set forth by the Commissioner shall and will be subject to the 3 day review period outlined in [1.1.1.3](#league-action-and-veto-power).

2. The Commissioner may set penalties for instances not strictly outlined in the Constitution, subject to [1.1.1.3](#league-action-and-veto-power).

3. Any and all penalties set by the Commissioner shall and will be for the good of the league and will be in line with the spirit and the intent of the league.

4. Should the Commissioner be found in violation of the rules and regulations of the Constitution or otherwise, penalties shall and will be agreed upon and enforced with a simple majority of 6 votes (out of 11). The Commissioner will have no veto authority in this situation.

### Roster Adjustment

1. The Commissioner has the authority to make adjustments to any and all team rosters only under the occasions outlined within the Constitution.

### Applicability and Retroaction

1. Any decision made by the Commissioner or by the league in his or her absence should be considered a one-time action unless otherwise specified. Similar situations following any decided action will continue to be subject to the rules and regulations contained in the Constitution.

2. These decisions will not be considered retroactive to similar situations prior to the decision.

##  Authority of the Constitution

###  Enacting and Application of Rules and Regulations

1. The rules and regulations contained within the statutes of the Constitution will be considered final as of the day of the league draft, prior to the first pick. No team owner, including the Commissioner, has the authority to override these conditions.

### Amendments to the Constitution {#amendments-to-the-constitution}

1. Prior to a new fantasy season draft and following the conclusion of the previous fantasy season, a Constitutional Summit, hereinafter referred to as rules summit, shall be held for the discussion of amendments to the Constitution.

2. The time and date for a rules summit will be set by the Commissioner and must take place at least 2 weeks before the date of the draft.

3. To hold a rules summit, a quorum of members must be present, either in person or electronically. If a quorum is not met, the summit will be postponed until such time that more members can be in attendance.

4. Any and all team owners may present a proposed amendment at the rules summit. Each proposal will be discussed and voted on by the members in attendance. The present members will vote by simple majority to add the proposed amendment to a list of Constitutional changes. This list must then go before all team owners to be voted on.
    a. An amendment to the Constitution will only be added with a 2/3 vote of the entire league and must be voted on prior to the day of the draft. Any and all Constitutional changes not voted on prior to the day of the draft will be rejected and must wait until the next rules summit for consideration by the league.
    
5. In addition to any proposed amendments, all decisions made by the Commissioner during
the previous fantasy season may be included for discussion as potential rule changes and
will be governed by the rules outlined in [1.2.2.4](#amendments-to-the-constitution).

6. For the duration of the rules summit, the Commissioner will be considered an equal member of the league and will not hold special voting or vetoing privileges.

7. All Constitutional changes will go in to effect the day of the draft, prior to the first pick. Any and all changes will not be considered retroactive.
    a. For approved changes to the Constitution regarding [the draft (Article 4)](#the-draft), [trades (Article 6)](#player-trades), and [keepers (Article 7)](#keepers), the effective date will still be the day of the draft, prior to the first pick.
    b. All actions taken before this date and time will be governed by the Constitution in its previous form.
    
# League Membership and Rules

##  Teams, Dues, and Fees

###  Number of Team Owners

1. The maximum number of teams eligible to be owned in the league is 12. The minimum number of teams eligible to be owned in the league is 12.

### League Dues and Assessed Fees

1. The league dues are set at $50 per team.

2. The league does not assess a fee for transactions of any kind, therefore a team owner will not be required to pay more than the $50 for league dues each year to continue owning their respective team.

3. Payment of league dues by each member is required by the start of each fantasy season. A penalty will be imposed on a team owner for not paying his or her league dues by this date.
	a. The assessed penalty for late payment is as follows:
		+ Before Week 1 - no penalty
		+ After Week 1 - a loss of 1 point for the negligent fantasy team in that week's head-to-head matchup.
		+ After Week 2 - a loss of 2 points for the negligent fantasy team in that week's head-to-head matchup.
		+ After Week 3 - a loss of 4 points for the negligent fantasy team in that week's head-to-head matchup.
		+ After Week 4 - a loss of 8 points for the negligent fantasy team in that week's head-to-head matchup.
		+ After Week 5 - a loss of 16 points for the negligent fantasy team in that week's head-to-head matchup.
		+ After Week 6 - dismissal from the league, only overturned by a unanimous vote of all owners.

	b. Any league member may volunteer to pay another owners league dues at any time, however he or she will take on that debt outside of the parameters of the league rules and regulations and collection of that debt will not be considered an issue pertinent to the operation of the league.
	c. A dismissal from the league does not require a refund of league dues. This can only be done at the discretion of the Commissioner and subject to [1.1.1.3](#league-action-and-veto-power).

4. The Commissioner may assess a one-time fee on any member as a result of a rule violation. The terms of the fee and payment will be decided by the Commissioner and will be subject to [1.1.1.3](#league-action-and-veto-power).

5. The Commissioner or any other member of the league may suggest the assessment of a onetime fee for the purposes of the improvement or the betterment of the league. These suggestions will be taken under review by the league and can only be passed by a unanimous vote. The intent of such a fee will be to increase the level of enjoyment, i.e. the purchase of a trophy for the league winner/loser, food or drinks for an event, or other discretionary expenses.

## Exiting Owners and New Owners {#exiting-owners-new-owners}

### Mid-Season Transfers {#mid-season-transfers}

1. In the event that an owner leaves the league for any reason during a fantasy season, the vacated ownership slot will immediately become available to a new owner and league member.

2. The Commissioner must act in good faith with the league to find a new team owner as soon as possible in an effort to make a smooth transition and not disrupt the operations of the league.

3. A new owner will be proposed to the league by the Commissioner and all members of the league must vote to accept or deny the proposal.

4. A 2/3 vote by the league members is needed to accept a new ownership proposal. Should the proposal be accepted, the new member will assume responsibility for the team immediately. Should the proposal be denied, the team will remain without an owner and the search for a new league member will continue.

5. The Commissioner will be responsible for managing and maintaining any vacated team until such a time as a new permanent owner can be presented and accepted per [2.2.1.2-4](#mid-season-transfers). In this situation the Commissioner will be held to all rules and regulations regarding team management and maintenance, however on matters of voting he will not be granted additional voting rights for the vacated team.
	a. Example: A team becomes vacated during the season and the Commissioner assumes operation of that team. Before a new owner can be found a situation arises that would require the voting of all team owners. The Commissioner is not allowed two separate votes based on the fact that he manages two teams. He or she will retain all original voting powers given to the Commissioner but no additional votes at any time, for any reason.

6. Any and all situations calling for a vote by the full league, be it a simple majority, a 2/3 vote, etc., during the period before a new owner has been chosen will be calculated using the total number of current owners, not the total number of teams in the league.
	a. Example: With the departure of 1 team owner from the league, majority and 2/3 will be calculated using 11 as the base number of votes. If there are 2 simultaneously vacated teams the base number of votes is reduced to 10, and so on and so forth.

7. A new owner will accept the team in the condition that it was vacated in, including any additions and/or deletions made by the Commissioner in the interim period. However, once a new owner has been approved by the league, he or she has the right to make changes to their team, subject to the rules and regulations in the Constitution.

8. The league dues assessed to a new owner will be calculated using the percentage of the remainder of the fantasy season once control of the team has been granted. This payment will be due in full by the end of the fantasy season.

9. New team owner dues may be distributed to the previous team owner as a refund at the discretion of the Commissioner. In the event that the previous team owner cannot be reached or that the Commissioner decides not to reimburse the previous owner, the money will be deposited in to a discretionary fund for the league's use.

10. Should a team become vacated and a new owner is not presented and approved before the end of the fantasy season, the Commissioner will retain management and maintenance responsibilities into the off-season until a new owner can be brought in to the league. Procedures and rules for off-season new member transfers are outlined in the following section. Any winnings granted to a team without an owner will be transferred to a
discretionary fund for the league.

11. The Commissioner may be removed as the interim team manager if he is found to be in violation of the Constitution by a unanimous vote of the remaining league members. In this situation the league will then be required to vote by a 2/3 majority for another current team owner to serve as the interim manager of the vacated team until a new team owner can be presented and approved.

### Off-Season Transfers {#off-season-transfers}

1. The rules and regulations outlined in the previous section will apply to off-season team ownership transfers as well, with the exception of the omission of subsections g through k. Because of the timing of an off-season ownership transfer, there are several procedural differences that are not addressed in the previous section.

2. If a new owner is approved prior to the Keeper Deadline set out in [7.1.2](#keeper-deadline) and no Keepers have yet to be chosen for the vacated team, a new team owner will accept the team in the condition that it was vacated in, including any additions and/or deletions made by the Commissioner in the interim period.

3. If a new owner is approved after the Keeper Deadline or if Keepers have been chosen before the team is vacated, that team will revert back to its status immediately following the end of the fantasy season, effectively making any and all Keeper decisions for the following fantasy season null and void. The new owner will have the option of making Keeper selections at the time of the transfer, even if the Keeper Deadline under [7.1.2](#keeper-deadline) has passed.
	  a. A new team owner may choose not to select any Keepers and begin the following fantasy season with all available player slots empty. Owners will otherwise be bound to the statutes outlined in the Constitution.
	  b. Should a team remain vacated by the date of the Keeper Deadline, the Commissioner, acting as the temporary team manager, will not make any Keeper selections for that team in anticipation of a new owner being selected by the league.
	  c. The Commissioner will also be prohibited from agreeing to any trades during this time frame involving Keepers and draft picks while acting as the temporary team manager.
	  
# Team Structure and Scoring Rules

## Roster Construction {#roster-construction}

### Player Position Slots

1. A complete starting lineup for any and all teams will consist of 9 scoring players (Team
Defense will be considered a scoring player)

2. All teams will consist of the following player positions (and number of available starting slots): Running Back (2); Quarterback (1); Wide Receiver (2); Tight End (1); Kicker (1); and Team Defense (1).

3. All teams will be provided one additional slot that is flexible to one of the following three positions: Running Back; Wide Receiver; and Tight End.

4. All teams will be provided a maximum of 7 bench slots that may filled using any combination of available players from any category.
    a. It is worth noting that certain host sites employ a maximum number of player position types that a team may possess.
    
### Injured Reserve Slot

1. All teams will be provided with an Injured Reserve (IR) slot.

2. An owner may move any injured player from his or her starting lineup or bench into the IR slot in order to create more available space while still maintaining ownership of the injured player.

3. IR-eligible players can only be moved to the IR slot from an owner's active roster or bench. Available players cannot be added directly to an owner's IR slot from free agency, as the owner must first add the player to an open bench slot.

4. A player will be eligible for the IR slot based on the NFL's official disabled list of active and inactive players.

5. Once a player has been moved into the IR slot, that player may reside there indefinitely so long as that player remains officially disabled and therefor unable to play.

6. If a player is placed into the IR slot and has remained there through the end of the fantasy season, that player may be chosen as a Keeper subject to the statutes outlined in [Article 7 (Keepers)](#keepers).

## Scoring {#scoring}

### Scoring Breakdown

1. A breakdown of scoring by player position is below:
    + Quarterback (QB) = 1 point for every 25 yards, or 0.04 points per yard
    + Running Back (RB) = 1 point for every 10 yards, or 0.1 points per yard
    + Wide Receiver (WR) = 1 point for every 10 yards, or 0.1 points per yard
    + Tight End (TE) = 1 point for every 10 yards, or 0.1 points per yard
    + Kicker (K) = 1 point for every Point After Touchdown (PAT); 3 points for every successful field goal between 0 and 39 yards; 4 points for every successful field goal between 40 and 49 yards; 5 points for every successful field goal 50 yards or more; -2 points for any and all unsuccessful field goal attempts.
    + Team Defense (DEF) = 1 point per sack; 2 points per interception; 2 points per recovered fumble; 2 points for every blocked punt, PAT, or field goal; 2 points for every safety; 6 points for every blocked punt or field goal returned for a touchdown; 6 points for every punt returned for a touchdown; 6 points for every kickoff returned for a touchdown; 6 points for every fumble returned for a touchdown; and 6 points for every interception returned for a touchdown.

2. The DEF position will begin each game with a total of 15 points. This consists of 10 points for 0 yards allowed and 5 points for 0 points allowed. As more yards are allowed and/or points are scored against that particular DEF, there will be a subsequent reduction in fantasy points.

3. All players, excluding DEF, will be subject to a 2 point reduction for every interception thrown or fumble lost.

### Other Rules and Regulations

1. All points scored by active players are based on fractional scoring. As an example, if a player receives 1 point for every 10 yards of rushing, each yard gained is worth 0.1 points and will be represented in the team's overall score. This applies to all player types.

2. Points earned for passing, rushing, and receiving are not restricted to a particular player position, excluding DEF. However, all point values for any scoring action will remain unaffected by player position.

3. The league is a Point Per Reception (PPR) league. All player positions excluding DEF will score an additional point for every reception made.

4. All successful 2 point conversion plays will result in 2 points for all player positions excluding DEF.

# The Draft

## Rules and Procedures

### Draft Style

1. The draft follows a standard snake format and consists of 16 rounds.

### Draft Pick Selection Time {#draft-pick-selection-time}

1. For rounds 1 and 2, each owner will have exactly 2 minutes to make their selection. For all proceeding rounds the clock will be set at 1 minute for each team owner.

2. Should the clock run down to zero without a selection being made, the Commissioner may impose a penalty on that team owner per [1.1.3](#league-violations-and-penalties).

### Absent/Late Team Owners

1. All team owners should be present for the draft.

2. A team owner who cannot make the live draft for any reason must make alternative
arrangements for the management of his or her draft.
    a. An absent team owner may join the draft via video conference through a computer or phone.
    b. An absent team owner may select a proxy to manage his or her draft selections. Decisions made by a proxy regarding any and all aspects of the draft will be considered final and not open for dispute or review.

3. A team owner arriving late will be granted an additional 2 minutes to make their selection for Rounds 1 through 3. For all rounds following Round 3, the team owner will be subject to the 1 minute maximum allowed for all members as outlined in [4.1.2](#draft-pick-selection-time), whether or not the owner has arrived to the draft.

4. If a team owner is in violation of any of the above rules and regulations, the Commissioner may impose a penalty on that team owner per [1.1.3](#league-violations-and-penalties).

### Location, Date, and Time

1. The time and date of the draft each year, as well as the location, must be chosen by the Commissioner no later than the date of the Keeper Deadline as defined in [7.1.2](#keeper-deadline). This will provide all league members with ample time to make scheduling arrangements.

2. The draft must be held no later than one week prior to and no earlier than 4 weeks prior to the opening weekend of the NFL regular season.

### Other Rules and Regulations

1. Keepers selected by a team owner will replace the pick of corresponding draft round value for that team as determined by the statutes in [Article 7 (Keepers)](#keepers).

2. Every owner must possess a full starting lineup by the conclusion of the draft. At a minimum, each owner must either draft and/or own through Keeper selection 1 QB, 2 RBs, 2 WRs, 1 TE, 1 DEF, 1 K, and 1 additional RB, WR, or TE by the conclusion of the draft.

## Pre-Draft and Post-Draft Periods

### Selection of Draft Order

1. To decide the order of the draft each year, a master list of 12 events and/or tasks to be completed will be created using input from all members of the league. Each member shall present at least 1 unique event or task at the next available summit/draft. All ideas will be discussed and 12 will be chosen in no particular order for the list.

2. The Commissioner will refer to the master list each subsequent year to determine the method of choosing the order for the next draft.

3. The rules and conditions of each particular challenge will not be defined in the Constitution, but they will be subject to discussion and agreement by members of the league, at the Commissioner's discretion.

4. If an event or task cannot be used, the Commissioner will convene a minimum of 1/3 of the league to stand as witness while an independent party draws the names of team owners from a container to decide the order of the following draft.

5. Once all draft order events and/or tasks have been used on the master list all options will become available again for use in subsequent years.

### Trading of Keepers for Draft Picks {#trading-of-keepers-for-draft-picks}

1. General rules and regulations regarding trading will be discussed in [Article 6 (Trades)](#player-trades). This section strictly refers to the trading of a Keeper(s) for a draft pick(s).

2. A team owner may trade one or more of his or her Keepers chosen in the off-season for an
equal number of draft picks from another team owner.
    a. This transaction must be equal and opposite. Any combination of this type of trade is allowed, i.e. 1 Keeper for 1 pick; 2 Keepers for 2 picks; 3 Keepers for 3 picks; 1 Keeper and 1 pick for 1 pick and 1 Keeper; and 2 picks and 1 Keeper for 2 Keepers and 1 pick.

3. The trade will be agreed upon by all parties involved and presented to the Commissioner. The Commissioner will be responsible for informing the remaining members of the league of the proposed transaction.

4. Once the league is notified of the proposal they will have exactly 24 hours to veto the trade by a majority vote. If no veto is issued the trade will stand.

5. Any trade involving draft picks for Keepers can be proposed prior to the first pick of the draft. No trades of any kind will be allowed once the draft has begun. A trade proposal issued within 24 hours of the start of the draft must be vetoed before the first pick of the
draft.

6. Regardless of the transaction, no player will be allowed to own more than 3 Keepers prior to the start of any fantasy football draft.

### Post-Draft Period

1. The period of time referred to as the Post Draft Period is defined as that time immediately following the draft and prior to the first week of the fantasy football season.

2. During this period no waiver acquisitions will be allowed.

3. Trading as outlined in [Article 6](#player-trades) will be not be restricted in any way, including during the Post Draft Period.

4. Starting on Tuesday of the first week of the fantasy football season, the Post-Draft Period will have ended, and all waiver acquisitions will be allowed and will follow the statutes outlined in [Article 5](#waiver-wire-acquisitions).

5. Once the Post Draft Period has concluded all regular season rules and regulations will become applicable and binding.

# Waiver Wire Acquisitions {#waiver-wire-acquisitions}

### Definition of Waivers {#definition-of-waivers}

1. Waivers is the time period by which a player must wait before becoming a free agent. Any player placed on waivers cannot be added by a team owner until that player's waiver period is concluded and he becomes a free agent.

2. All players not drafted by any team in the league following the draft will be immediately placed on waivers.
    a. No player will be considered a free agent until the conclusion of the Post-Draft Period.

3. For the duration of the fantasy football season, any and all unowned players each week will also be placed on waivers at the start of their individual game times in that particular week and will remain on waivers until the waiver period ends in the following week.

4. Any and all players dropped by a team owner will also be immediately placed on waivers until 3 a.m. the following morning.

### Acquisition Budget

1. Teams will have a budget of 200 spooky bucks ($200) with which they can bid to make player acquisitions.

2. If a team would like to add a player, that team will secretly bid an amount they are willing to pay any time before waivers are processed per the waiver regulations in [5.0.3](#waiver-regulations). When waivers are processed, the manager with the highest bid will be awarded the player, and the bid will be subtracted from that team's budget.

3. Spooky bucks are non-transferable and can be used only to acquire players on the waiver wire via blind auction.

4. Team owners can place a bid on a player for $0.

### Process and Regulations {#waiver-regulations}

1. Excluding the first week of the fantasy football season all waiver wire bids for players from the prior week's games will be processed at 3 a.m. Wednesday morning of that week. Any and all dropped players after this time each week will be placed on waivers for one day as stated in the previous Section.
    a. Because of the one-day waiver period for all dropped players, any and all players dropped from a team by an owner the day of said player's individual NFL game will remain on waivers until the following week's initial waiver period has concluded.

2. Beginning in Week 1 of the fantasy football season, any owner may place a bid on any player on the waiver wire.

3. Acquisition requests by owners for players on waivers will processed based first on the bid amount and second on waiver priority.
    a. The team owner which places the highest bid on a player will acquire the player.
    b. If a player on waivers has an equal bid from more than one team owner, the owner with the higher priority that week will acquire the player.
	  c. All players unclaimed after their respective waiver periods end will become free agents and can be added by any team owner on a first-come, first-served basis.
	  
### Determining Waiver Wire Priority

1. Week 1 Priority Order
    a. At the conclusion of the Post Draft Period owners will be able to make acquisitions from the waiver wire for their individual teams prior to the start of the Week 1 fantasy football games.
    b. The priority order for Week 1 is determined using the inverse of the draft order for that year.

2. Regular Season Priority Order
    a. Following the first week of the fantasy football season, waiver priorities will be determined by the inverse order of the league standings each week. This order will be reset each week during the season to reflect any and all changes in standings.
    
# Player Trades {#player-trades}

### Trading Periods and Deadlines

1. Immediately following the draft each year any team owner may propose a trade to any other team owner.

2. Any and all trades must be completed by the date of the Trade Deadline which will be set each year by the Commissioner.

3. Following the Trade Deadline, no team owner will be allowed to make a trade with another owner until the next Keeper Deadline outlined in [7.1.2](#keeper-deadline).
    a. After the date of the Keeper Deadline owners will be allowed to trade Keepers for draft picks and vice versa, excluding the terms governed by [2.2.2.3](#off-season-transfers) for the Commissioner as acting manager of a vacated team.

### Procedures and Rules

1. Any and all players owned by any team may be offered in a trade. This includes injured or suspended players in addition to active players.

2. A trade between two team owners may involve an odd number of players, i.e. 1 player for 2 players, or 3 players for 2 players.
    a. Trades involving an uneven number of players must be in line with the roster limitations set out in [3.1](#roster-construction).
    b. For example: If a team owner is trading one player to another team and receiving two players in return, that owner must have room for that additional player on his or her roster while not violating the maximum number of players allowed on a team.

3. After a trade has been proposed, the owner being offered the trade will have a period of several days to accept or decline the trade offer.

4. Once a trade proposal has been accepted, the remaining owners in the league may vote by a 2/3 majority to veto the trade.
    a. Because neither owner involved in the trade will be allowed to vote, the standard vote count to issue a veto will be 7 out of 10 in favor of the veto.
    b. Any trade is subject to intervention by the Commissioner should he decide further action is required. This action in turn will be subject to [1.1.1.3](#league-action-and-veto-power).

5. Trades between Keepers and draft picks are discussed in [4.2.2](#trading-of-keepers-for-draft-picks).

# Keepers {#keepers}

## General Rules and Regulations

### Definition of a Keeper

1. After the conclusion of every fantasy football season each owner will choose at a minimum 1 and a maximum of 3 players from his or her team to keep for the following fantasy football season.
    a. Trading one or more of a team's Keepers during the offseason to another team owner for draft picks in the following league draft is permitted, however a team must at all times maintain ownership of at the least 1 Keeper until the conclusion of that draft.
    b. A team will never be allowed to roster more than 3 Keepers prior to that year's league draft.
    c. A team will be allowed to remove a player from their keeper list after the keeper deadline and prior to the draft, however a team must at all times maintain ownership of at least 1 keeper until the conclusion of that draft.

2. Once the draft has been completed any and all Keepers may be traded to another owner, dropped from their current team, or added to the team through normal trading procedures outlined in [Article 6](#player-trades).
    a. All players drafted are considered draft picks, not keepers, at the conclusion of the draft. The minimum and maximum limitations will not apply until the following Keeper Deadline when the team owner must choose Keepers for the next year.

### Keeper Deadline

1. Keeper selections for all teams must be made by 11:59 p.m. on July 4 of every year.

2. An owner may submit their Keeper selections to the Commissioner either through the host website or in writing at any time prior to the end of the day on July 4 of each year.

3. If an owner does not submit a list of a minimum of 1 and a maximum of 3 Keepers to the Commissioner by the Keeper Deadline, the Commissioner will penalize that team owner accordingly.

4. For rules and regulations concerning vacated teams at the point of the Keeper Deadline, please refer to [2.2.2.3](#off-season-transfers).

### Trading Keepers

1. See [4.2.2](#trading-of-keepers-for-draft-picks)

### Eligibility

1. A player is eligible to be kept for the next fantasy football season by a team owner if that player satisfies one of the following conditions:
    + The player has been ruled by the NFL as active and eligible to play for at least one week while a member of the owner's team, either in the starting roster or the bench, hereinafter referred to as the Active Player Rule.
    + The player was originally drafted by the current owner and has remained on his or her team for the entirety of the season, either on the starting roster, the bench, or in the IR slot. This is the one and only exception to the Active Player Rule.

2. If an owner drafts a suspended or injured player, and then drops that player without the player ever being ruled by the NFL as active and eligible to play, and if that owner then subsequently acquires that player from free agency at any time, the player must now abide by the Active Player Rule for that team in order to be kept. The exception to the Active Player Rule will have no meaning here because the player was temporarily dismissed from the owner's team.

3. Any player drafted in the 1st Round or valued as a 1st Round draft pick, i.e. a Keeper from the previous season, will not be allowed to be kept by any team under any circumstance for the following season.

## Draft Implications

### Draft Value for Keepers {#draft-value-for-keepers}

1. Any player selected by an owner as a Keeper for the following year will represent one draft pick in that year's upcoming draft for that owner.

2. The draft value of that player is determined by several factors:
    + If the proposed Keeper has been owned by the team for the entirety of the season, the draft value of that player will be one round higher than that of the previous year. 
    + If the proposed Keeper was acquired through a trade of any kind with another owner during the season and satisfies the Active Player Rule, the draft value of that player will be one round higher than that of the previous year, excepting those players under the Revalued Player Rule discussed in [7.2.2](#the-revalued-player-rule) below.
    + If the proposed Keeper was acquired through free agency and satisfies the Active Player Rule and does not conflict with the Revalued Player Rule, the draft value of that player will be a 10th Round pick.

3. If a team owner decides to keep 2 or more players with the same draft value for that year's upcoming draft, the owner will designate one of the players to retain that value. Each of the other players will then be valued 1 consecutive round higher.

4. No team owner will be allowed to keep 2 or more players with 1st Round values for that year's upcoming draft.

### The Revalued Player Rule {#the-revalued-player-rule}

1. All players remaining undrafted at the conclusion of the draft will be considered free agents and are eligible to be added to any team by the rules and regulations outlined in [Article 5 (Waiver Wire Acquisitions)](#waiver-wire-acquisitions).

2. Any player chosen from free agency following the draft will constitute a 10th Round draft value if kept for the next fantasy season as outlined in [7.2.1.2](#draft-value-for-keepers).

3. Players that have been drafted to a team and then subsequently dropped from that team become free agents per the rules outlined in [5.0.1.4](#definition-of-waivers).

4. The Revalued Player Rule states that any player drafted in rounds 2 through 16 who becomes a free agent during the fantasy football season will have their draft value reduced to the base level of 10th Round as outlined in [7.2.1.2](#draft-value-for-keepers), so long as that player remains a free agent for more than 2 weeks.
    a. If the player is added to a team by an owner through free agency and that player has not remained in free agency for more than 2 weeks, the player will retain the draft value he had before being cut from the former team.
        + Example 1: Player A was taken in the 3rd Round of the draft. Player A was cut from that team 4 weeks into the fantasy season. Player A is then added 1 week later by another team owner. Should the new owner decide to make Player A his or her Keeper for the next season, Player A will command a 2nd Round draft value.
        + Example 2: Player A was taken in the 5th Round of the draft. Player A was cut from that team 4 weeks into the fantasy season. Player A is then added 3 weeks later by another team owner. Should the new owner decide to make Player A his or her Keeper for the next season, Player A will command a 10th Round draft value.
        + Example 3: Player A was taken in the 15th Round of the draft. Player A was cut from that team 4 weeks into the fantasy season. Player A is then added 1 week later by another team owner. Should the new owner decide to make Player A his or her Keeper for the next season, Player A will command a 14th Round draft value.
        + Example 4: Player A was taken in the 15th Round of the draft. Player A was cut from that team 4 weeks into the fantasy season. Player A is then added 3 weeks later by another team owner. Should the new owner decide to make Player A his or her Keeper for the next season, Player A will command a 10th Round draft value.
    b. The only exception to the Revalued Player Rule is as follows: If an owner drops a drafted player from his or her team and then chooses to re-add that same player, and no other owner has added that player in the interim, that player must remain a free agent for more than 3 weeks, not 2 under the normal rule, to have his draft value reduced to 13th Round for the original owner.
        + Example 5: Player A was taken in the 3rd Round of the draft. Player A was cut from that team 4 weeks into the fantasy season. Player A remains in free agency and is then added back to the original team 2 weeks later. Should the team owner decide to make Player A his or her Keeper for the next season, Player A will command a 2nd Round draft value.
        + Example 6: Player A was taken in the 5th Round of the draft. Player A was cut from that team 4 weeks into the fantasy season. Player A remains in free agency and is then added back to the original team 4 weeks later. Should the team owner decide to make Player A his or her Keeper for the next season, Player A will command a 10th Round draft value.
        
# Regular Season

### General

1. The schedule for each fantasy season is chosen at random by the host site. Once the schedule has been set, there can be no adjustments or changes to any head-to-head matchups in the regular season.

2. The regular season will be 13 weeks long, beginning with the first week of the NFL regular season and will last through Week 13.

3. All teams will be placed in the same Division, and the overall top 6 teams at the end of the regular fantasy season will compete in the fantasy playoffs for the championship.

### Head-to-Head Matchups {#head-to-head-matchups}
1. Each team will compete in a head-to-head matchup each week of the regular fantasy season.

2. The winner of each matchup will be determined by the total points scored from each player a team's starting lineup.

3. For a list of scoring rules, see [3.2](#scoring).

4. Should the two teams end in a tie at the end of the final game that week, the total points scored by all bench players for each team will be used to break the tie.
    a. If a player currently in the owner's IR slot becomes activated and scores any points that week, those points will not be included in the total bench points for that team.

5. If both teams remain tied after adding in their total bench points, both teams will receive a tie for that week.

### Overall Rankings {#overall-rankings}

1. Overall rankings will be determined in the following order: the win/loss/tie records of each team; total points scored; and total points against.

2. Overall rankings will be used to determine playoff teams and their respective rankings at the end of the regular fantasy season. If all other tie-breakers have been exhausted and a tie still remains, the Commissioner will tally all bench points for, and then finally all bench points against to determine the final overall rankings.
    a. If a tie still remains the Commissioner will assign a challenge or event outside of the scope of fantasy football to determine the final rankings. This decision will be final and not subject to the statutes in [1.1.1.3](#league-action-and-veto-power).

### Maintaining an Active Roster

1. All owners will be expected to maintain an active roster at all times during the fantasy football season, including the playoffs, to the best of their ability.

2. An active roster is defined by a full starting lineup each week of active and eligible players.

3. If a team owner does not maintain an active roster for more than 3 weeks, he or she will be subject to penalization by the Commissioner outlined in [1.1.3](#league-violations-and-penalties).

4. There are some situations that may warrant violating this rule which is why a 3 week inactive roster period is allowed:
    + An owner might have all of one player type on a bye and, rather than dropping a desired player from his or her team, will simply not start a player at that position.
    + An owner may have a player become injured prior to the start of that particular game and might not have time to insert a new player.
    + An owner might be incapable of logging in to the host site to make lineup changes prior to the start of a scheduled game.

5. In the event of a vacated team, the Commissioner will assume responsibility of that team until a new owner can be approved per [2.2.1](#mid-season-transfers) and will be subject to the same rules in this section for that team as well as his or her own team.

# Playoffs and Payouts

### Champion's Bracket Schedule

1. The Fantasy Football Playoffs, hereinafter referred to as the playoffs, will consist of 3 rounds and 6 teams.

2. The 2 highest ranked teams will receive a bye for the first week of the playoffs.

3. Week 1 of the playoffs will consist of the 3rd ranked team verses the 6th ranked team and the 4th ranked team verses the 5th ranked team.

4. Week 2 of the playoffs will consist of the 1st ranked team verses the Week 1 winner between the 3rd and 6th ranked teams and the 2nd ranked team verses the Week 1 winner between the 4th and 5th ranked teams.

5. Week 3 will be the championship game between the 2 winners of Week 2.

### Loser's Bracket Schedule

1. The 4 lowest ranked teams in the league will compete in a 2 week playoff for last place in the league.

2. Week 1 of the loser's bracket playoffs will consist of the 12th ranked team verses the 9th ranked team and the 11th ranked team verses the 10th ranked team.

3. Week 2 will consist of the 2 losing teams in Week 1 of the loser's bracket playoffs and will decide the last ranked team for that fantasy season.

### Scoring and Tie-Breakers

1. The playoffs will follow the same rules for determining a winner as outlined in [8.0.2.1-4](#head-to-head-matchups) and [8.0.3.2](#overall-rankings).

### Payouts

1. The winner of the fantasy football season will receive $500.

2. The second place team will receive $100.

3. The last place team will be subject to a penalty decided on by the league. The terms and conditions of this penalty will be discussed and voted on for approval by a 2/3 vote of the entire league prior to the Keeper Deadline of July 4 of each year.
    a. Enforcement of this penalty will be at the discretion of the Commissioner and the members of the league, and the rules for enforcement will not be addressed in the Constitution.
    
# Other Rules and Regulations

### Player Lock-Ins

1. A player will be locked in to his fantasy roster position at the start of that player's individual NFL game each week and will not be allowed to be moved from that position in the team's roster until 3 a.m. following the final NFL game that week.
    a. In the event that a team owner cannot make a roster change in a timely manner, he or she may contact the Commissioner to make any allowable adjustments for that team.
    b. The Commissioner will decide if the request is valid.
    c. If the Commissioner cannot be reached or is unable in any way to make the requested roster adjustments on behalf of the team owner, the owner must send any and all requested roster changes to all members in a text message.
    d. Any roster adjustment requests made in the above manner will still be subject to the Player Lock-In rule. The requesting owner must show proof of the time of the request for the adjustments to be valid.
    